@startuml

entity USER {
    Id
    Login
    Email
    Password_hash
}

entity DEVICE {
    Id
    User_Id
    Type
    Custom_name
}

entity TELEMETRY_RECORD {
    Id
    Device_Id
    Name
    Value
}

entity CONTROL_PARAM {
    Id
    Device_Id
    Name
    Value
}

USER ||--o{ DEVICE
DEVICE ||--o{ TELEMETRY_RECORD
DEVICE ||--o{ CONTROL_PARAM

@enduml
